### ISSUE TITLE
Persist new refresh token after previous token has been used

### ISSUE THREAD

**Issue by aolik08** [nioc/netatmo-collector#2]
Hello,

As I am not a php developer I thought I ask for some help. A breaking change of Netatmo Api authentication is in place since yesterday (without any prior notice, of course) web generated refresh_tokens are no more permanent tokens, they are automatically renewed on every request. So maybe a way to upgrade the config.php file with the refresh token should be found

**Comment by nioc** [comment]
Hello,

I can see 2 ways to solve this problem:
- storing username and password in config.php? But it was advised by Netatmo not doing this because it expose your user credentials (need file ACL).
- update refresh_tokens after each request? But what happens if you do request only once a day and refresh token expired?

What is your proposal?

**Comment by nioc** [comment]
Mmmh, may be we just need to store the new refresh tokens after using the previous.

**Comment by aolik08** [comment]
Hello!

I see Client Credential is deprecated since last year. https://dev.netatmo.com/apidocumentation/oauth
now the documentation is not very clear on it, but from my understanding, in my case at least, since I only want to get the data and display it nicely in a grafana dashboard, I need to create an app for that on netatmo side, generate an access_token and a new_refresh_token using the current refresh_token, my_app_id as the client_id and my_app_secret as the client_secret. Next time I make a request on their api i have to use the previously received refresh_token (new_refresh_token in my example) together with my_app_id and my_app_secret to get the current access token and a new refresh_token to be used next time.
I fully agree that if i have an internet outage for more than 3hrs, manual steps are to be used to manually generate a new refresh and access tokens to be used, but hey...it's netatmo way
but maybe somehow updating the tokens in tokens.json file with the newly received ones should be enough for now :)

**Comment by nioc** [comment]
I'll look at it tonight.
Do you know if unused refresh token expires after some time?

**Comment by aolik08** [comment]
Unfortunately i don't know. I am hopping that expires in 10800 seconds applies to access token only, otherwise i can't see the logic of having 2 tokens. 
Reading a little bit more about oauth2, it seems that refresh token is a one time use only token to prove the service/api that you are the authenticated user, without being forced to rentering the credentails again, so the api can generate another short lived ("expires_in") access_token even after the previous access_token has already expired. 

Thank you

**Comment by nioc** [comment]
Yes it is a valid OAuth2 pattern but removing password grant_type without updating their PHP API (used in this library) is a very annoying move on Netatmo's part.
As I can see [here](https://github.com/Netatmo/Netatmo-API-PHP/issues/44), there is a way described in [this post](https://forum.netatmo.com/viewtopic.php?p=94776#p94776):
- go to the [apps dev page](https://dev.netatmo.com/apps)
- set the scope to `read_station`
- ask a token, paste it in the token.json --> working for 3 hours.

They also said that the token does not expire until it is used.

I got a error 400 before recreating a token (I assume it must have been authorized with the authorization_code grant process before use).

So now, I have to store the new refreshed token, and it should be ok.

**Comment by nioc** [comment]
Version 0.4.0 should solve the problem. If it doesn't, let me know by reopening the issue.

**Comment by aolik08** [comment]
thank you for your prompt fix
